import React from 'react'
class Terms extends React.Component{
    render(){
        return(
            <div className='t-and-c'>
                <br/><br/>
                <div className="container">
                <div id="Terms-and-Conditions">
                <h1 className="mt-5" >Terms of Use</h1>
                <p class="western">Welcome to Kuants Wealth Private Limited Kuants, a registered trademark of Kuants Wealth Private Limited, provides a web-based platform aimed at helping its users to develop trading strategies. As a platform, it&rsquo;s a place to write and test trading algorithms. Your access and use of Kuants Wealth Private Limited subject to the Terms of Use set forth below. In the document below, Kuants Wealth Private Limited and Kuants have used interchangeability.</p>
                <p class="western">These Terms of Use constitute an agreement between Kuants Wealth Private Limited ("Kuants Wealth Private Limited", "us" or "we") and you (&ldquo;you&rdquo;), the individual listed in the account registration form the completion of which requires you to click the applicable &ldquo;I Agree&rdquo; box, and sets forth the terms and conditions that govern your use of kuants.in (the "Site") and/or any related services (the "Services") accessed through the Site.</p>
                <p class="western">We refer to these Terms of Use as the &ldquo;Agreement.&rdquo; We may update or amend these Terms of Use from time to time by posting such updates or amendments to the Site. Your use of the Site or any Services after we post any such updates or amendments will constitute your agreement to those updates or amendments.</p>
                <p class="western">Unless otherwise specified, Kuants Wealth Private Limited grants to you a non-exclusive and non- transferable limited right and license to access the Site and use the Services for your personal use or for your internal business purposes (but not on behalf of any third party) provided that you agree with and comply fully with the provisions of this Agreement. Certain features of the Site or Services are available only to users who register for a Kuants Wealth Private Limited account (&ldquo;Registered Users&rdquo;).</p>
                <p class="western">0. Kuants is only a technology platform. It does not act as a financial advisor, tax planner, distributer, wealth manager, investment advisor or any other form that related to capital management and all its verticles. We solely provide software and cannot be held liable in case of any loss caused due to any user activity.</p>
                <p class="western">1. Accounts, Passwords, and Security.</p>
                <p class="western">To become a Registered User, you must complete the registration process by providing Kuants Wealth Private Limited with current, complete and accurate personally identifiable information, including, without limitation, your real name and the email address through which we can correspond with you, as prompted by the applicable registration form. You further agree to keep any registration information you provide to Kuants Wealth Private Limited current, complete and accurate. As part of the registration process, you are entirely responsible for maintaining the security and confidentiality of your account information, including your username and password. Furthermore, YOU ARE ENTIRELY RESPONSIBLE FOR ANY AND ALL ACTIVITIES AND CONDUCT, WHETHER BY YOU OR ANYONE ELSE, THAT ARE CONDUCTED THROUGH YOUR ACCOUNT. We may hold you liable for any losses incurred by Kuants Wealth Private Limited or any other party due to someone else&rsquo;s use of your account or password. You agree to notify Kuants Wealth Private Limited immediately upon your becoming aware of any unauthorized use of your account or any other breach of security involving your account. Kuants Wealth Private Limited will not be liable for any loss that you or any other party may incur as a result of someone else&rsquo;s use of your password or account, either with or without your knowledge.</p>
                <p class="western">We use the term &ldquo;Content&rdquo; to mean entire or partial algorithms, code and code segments, trading strategies, data transformations, data analysis and manipulation functions, tools, software, data, databases, text, messages, images, graphics, video files, audio files, ideas, and other information and materials.</p>
                <p class="western">&nbsp;</p>
                <p class="western">2. Prohibited Activities.</p>
                <p class="western">We use the term &ldquo;Content&rdquo; to mean entire or partial algorithms, code and code segments, trading strategies, data transformations, data analysis and manipulation functions, tools, software, data, databases, text, messages, images, graphics, video files, audio files, ideas, and other information and materials.</p>
                <p class="western">Other than as provided at the end of this Section in respect of Shared Content, you acknowledge and agree that you will not:</p>
                <p class="western">&bull; copy, modify, publish, transmit, distribute, transfer or sell, create derivative works of, or in any way exploit, any of the Content accessible through the Site not submitted or</p>
                <p class="western">provided by you, including by use of any robot, spider, scraper, scripting, deep link or other similar automated data gathering or extraction tools, program, algorithm or methodology, unless you obtain Kuants Wealth Private Limited&rsquo;s prior written consent;</p>
                <p class="western">&bull; use the Site or Services to advertise, market, sell, or otherwise promote any commercial enterprise that you own, are employed by or are otherwise compensated by, either directly or indirectly;</p>
                <p class="western">&bull; use any engine, software, tool, agent or other device or mechanism to navigate or search the Site, other than the search engines and agents available through the Service and other than generally available third party web browsers;</p>
                <p class="western">&bull; copy, reverse engineer, reverse assemble, otherwise attempt to discover the source code, distribute, transmit, display, perform, reproduce, publish, license, create</p>
                <p class="western">derivative works from, transfer or sell any information, software, products or services obtained through the Site or the Services;</p>
                <p class="western">&bull; access the Site or use the Services by any means other than through Kuants Wealth Private Limited-provided or approved interfaces;</p>
                <p class="western">&bull; transmit any Content that is unlawful, harmful, threatening, abusive, harassing, tortious, defamatory, vulgar, obscene, libelous, or otherwise objectionable or which may invade another's right of privacy or publicity;</p>
                <p class="western">&bull; post or transmit any material that contains a virus, worm, Trojan horse, or any other contaminating or destructive feature;</p>
                <p class="western">&nbsp;</p>
                <p class="western">&bull; post or transmit information protected under any law, agreement or fiduciary relationship, including but not limited to proprietary or confidential information of others;</p>
                <p class="western">&bull; use any of the Site&rsquo;s or Service's communications features in a manner that adversely affects the availability of its resources to other users;</p>
                <p class="western">&bull; post or transmit any unsolicited advertising, promotional materials, "junk mail", "spam," "chain letters," "pyramid schemes" or any other form of solicitation or any non-resum&eacute; information such as opinions or notices, commercial or otherwise;</p>
                <p class="western">&bull; access or use the Site or Services to intentionally or unintentionally violate any applicable local, state, national or international law, including, but not limited to, regulations promulgated under any such law;</p>
                <p class="western">&bull; upload or transmit any material that infringes, violates or misappropriates any patent, trademark, service mark, trade secret, copyright or other proprietary rights of any third party or violates a third party&rsquo;s right of privacy or publicity;</p>
                <p class="western">&bull; manipulate or otherwise display or obstruct portions of the Site and/or the Services by using framing or similar navigational technology;</p>
                <p class="western">&bull; register, subscribe, attempt to register, attempt to subscribe, unsubscribe, or attempt to unsubscribe, any party for any Kuants Wealth Private Limited product or Service if you are not expressly authorized by such party to do so;</p>
                <p class="western">&bull; use the Site and/or the Services for any purpose that is unlawful or prohibited by these terms and conditions;</p>
                <p class="western">&bull; use the Site or the Services in any manner that could damage, disable, overburden or impair Kuants Wealth Private Limited&rsquo;s servers or networks, or interfere with any other user's use and enjoyment of the Site and/or the Services;</p>
                <p class="western">&bull; attempt to gain unauthorized access to any of the Site, Services, accounts, computer systems or networks connected to Kuants Wealth Private Limited through hacking, password mining or any other means;</p>
                <p class="western">&bull; obtain or attempt to obtain any Content through any means not intentionally made available as Shared Content through the Site or the Services; or</p>
                <p class="western">&bull; knowingly provide any Content that is false or inaccurate or will become false or inaccurate at any time.</p>
                <p class="western">&bull; Notwithstanding the prohibition on any of the above activities, we want to foster a community where Registered Users exchange and share Content that they have the</p>
                <p class="western">right to make public. Accordingly, you are permitted to copy, modify, use, comment on and / or republish, both on and off the Site and Services, reasonable amounts of Shared Content for purposes consistent with our mission to help people write, test and improve their algorithms or for other personal use (unless Kuants Wealth Private Limited has expressly agreed to other users in writing.) If you do copy, modify, comment on or republish Shared Content posted by another Registered User or Kuants Wealth Private Limited, you must (a) attribute authorship of that Shared Content to such Registered User or Kuants Wealth Private Limited and (b) provide the link to the appropriate URL on the Site at which you accessed the Shared Content. All comments that you post to the Site should be respectful of others and in all cases subject to the restrictions and guidelines of good behavior outlined in this Section 3. To be clear, the license to copy, modify and/or republish any Content that you have not authored is limited to the Shared Content for the above-stated purposes and use. You are not permitted and are expressly prohibited from copying, modifying, and republishing the Content of Kuants Wealth Private Limited and its other Registered Users except as expressly permitted above. Should a question arise in the future as to what does or does not constitute Shared Content, or how it may be used, you may contact us per the last bullet of Section 16 of this Agreement. We also reserve the right to provide public or individual notice about this issue and in any case, Kuants Wealth Private Limited&rsquo;s decision about Shared Content will control.</p>
                <p class="western">We reserve the right to cancel your account with us, without any notice to you as provided in Section 19, if we suspect any violation of any of the terms of this Agreement.</p>
                <p class="western">&nbsp;</p>
                <p class="western">3. Proprietary Rights.</p>
                <p class="western">Unless you choose to share your Content, we will use reasonable best efforts to keep your Content private. With respect to this Agreement, Kuants Wealth Private Limited may access, review, share, or otherwise make use of private Content in the following circumstances but not limited to (including in source code or similar form):</p>
                <p class="western">&bull; If necessary in the course of providing technical support or other maintenance of the Services; provided that, wherever possible, any access by Kuants Wealth Private Limited for technical support or maintenance purposes will be restricted to the very specific technical purpose relevant to such support or maintenance;</p>
                <p class="western">&bull; In order to comply with any applicable legal or regulatory requirements or court order;</p>
                <p class="western">&bull; In the event that we consider, in our discretion, that such Content may present a security risk;</p>
                <p class="western">&bull; In the event that we consider, in our discretion, that such Content may constitute an infringement or misappropriation of any third party right; or</p>
                <p class="western">&bull; In the event that we consider, in our discretion, that such Content may be relevant to Kuants Wealth Private Limited&rsquo;s defense in any legal proceeding.</p>
                <p class="western">&nbsp;</p>
                <p class="western">4. Feedback</p>
                <p class="western">In the event that you provide us any ideas, thoughts, criticisms, suggested improvements or other feedback related to our Site or Services (collectively "Feedback"), you agree we may use the Feedback to modify our products and services and that you will not be due any compensation, including any royalty related to the product or service that incorporates your Feedback. You grant to us a worldwide, sublicensable, assignable, royalty-free, fully paid, perpetual, irrevocable right and license to make, have made, use, reproduce, modify, translate, distribute, transmit, create derivative works of, perform, display, import, sell, offer for sale, make, have made and otherwise exploit, without the requirement to make any payment to you or to any third party or the need to seek any third party permission, the Feedback in any form, media, or technology, whether now known or hereafter devised or developed, and to allow others to do the same. This is true whether you provide the Feedback in any Content submitted publicly or privately, email or any other method of communication with us unless we have entered into a separate written mutual agreement with you that provides otherwise.</p>
                <p class="western">&nbsp;</p>
                <p class="western">5. Privacy and Security.</p>
                <p class="western">We are committed to your privacy and security. For more information, you should review our Privacy Policy at https://kuants.in/policies#privacy. By agreeing to these Terms of Use, you acknowledge that you understand that "perfect security" cannot be attained on the Internet, and that you understand and agree that we only agree to take reasonable steps to help ensure the security of your personal information and that such steps do not guarantee that the Site and the Services are invulnerable to all security breaches or immune from viruses, security threats or other vulnerabilities. We do not warrant that your information will be secure.</p>
                <p class="western">&nbsp;</p>
                <p class="western">6. Disclaimer of Warranties.</p>
                <p class="western">THE SITE AND THE SERVICES, AND ANY CONTENT, TOOLS, PRODUCTS OR SERVICES DISPLAYED, ACCESSED OR OBTAINED ON OR THROUGH THE SITES AND SERVICES ARE PROVIDED "AS IS", "AS AVAILABLE", AND WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING, WITHOUT LIMITATION, WARRANTIES OF TITLE, NON-INFRINGEMENT, SYSTEM INTEGRATION, AVAILABILITY, INTEGRITY, RELIABILITY OR TRANSMISSION OR RESPONSE TIME, DATA ACCURACY, AVAILABILITY, COMPLETENESS, RELIABILITY OR TIMELINESS, SUITABILITY OF CONTENT OR SERVICES, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. WITHOUT LIMITING THE GENERALITY OF THE FOREGOING, Kuants Wealth Private Limited AND ITS AFFILIATES, SUPPLIERS, AND AGENTS DO NOT WARRANT AND EXPRESSLY DISCLAIM THAT: (i) YOUR USE OF THE SITES AND/OR SERVICES AND</p>
                <p class="western">&nbsp;</p>
                <p class="western">ACCESS TO AND USE OF ALL OF THE TOOLS AND FEATURES THEREON WILL BE UNINTERRUPTED, TIMELY, ERROR-FREE, OR SECURE, (ii) THAT ANY INFORMATION OBTAINED THEREIN IS ACCURATE, RELIABLE, COMPLETE OR TIMELY, (iii) THAT DEFECTS WILL BE CORRECTED, OR (iv) THAT ANY SOFTWARE, SERVICES, SITES OR SERVER(S) ON WHICH THE SERVICES AND SITES ARE HOSTED ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. YOUR USE OF THE SITE AND THE SERVICES AND ANY CONTENT PROVIDED ON OR THROUGH THE SITES AND SERVICES ARE ENTIRELY AT YOUR OWN RISK, AND YOU SHALL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR PROPERTY OR PERSON, INCLUDING, BUT NOT LIMITED TO, YOUR COMPUTER SYSTEM AND ANY DEVICE YOU USE TO ACCESS THE Kuants Wealth Private Limited SITE, SERVICES OR BROKERAGE CONNECTION SERVICES, OR ANY OTHER LOSS THAT RESULTS FROM ACCESSING SUCH CONTENT. From time to time, we may offer new &ldquo;beta&rdquo; features or tools with which Registered Users may experiment. Such features or tools are offered solely for experimental purposes and without any warranty of any kind and may be modified or discontinued at our sole discretion. The provisions of this Section apply with full force to such features or tools.</p>
                <p class="western">YOU ACKNOWLEDGE AND AGREE THAT WE ARE NOT LIABLE, AND YOU AGREE NOT TO SEEK TO HOLD US LIABLE, FOR THE CONDUCT OF THIRD PARTIES, INCLUDING OPERATORS OF OTHER SITES ACCESSIBLE THROUGH THE SITE OR SERVICES, AND THAT THE RISK OF INJURY FROM SUCH THIRD PARTIES RESTS ENTIRELY WITH YOU. WE MAKE NO WARRANTY THAT ANY GOODS OR SERVICES PROVIDED BY THIRD PARTIES IN CONNECTION WITH YOUR ACCESS AND USE OF THE SITE AND SERVICES WILL MEET YOUR REQUIREMENTS OR BE AVAILABLE ON AN UNINTERRUPTED, SECURE, OR ERROR-FREE BASIS. WE MAKE NO WARRANTY REGARDING THE QUALITY OF ANY SUCH GOODS OR SERVICES, OR THE ACCURACY, TIMELINESS, TRUTHFULNESS, COMPLETENESS OR RELIABILITY OF ANY USER CONTENT OBTAINED THROUGH THE SITE AND/OR THE SERVICES.</p>
                <p class="western">YOU ARE SOLELY RESPONSIBLE FOR ALL OF YOUR CONTENT AND COMMUNICATIONS AND INTERACTIONS WITH OTHER USERS OF THE SITE AND SERVICES. OTHER THAN TO EVALUATE THE PERFORMANCE OF ALGORITHMS FOR COMPLIANCE WITH OUR CONTEST RULES AND POSSIBLE ALLOCATION TO YOU UNDER SEPARATE LICENSE, YOU UNDERSTAND THAT WE DO NOT MAKE ANY ATTEMPT TO VERIFY ANY CONTENT POSTED ON THE SITE BY YOU OR ANY OTHER USERS.</p>
                <p class="western">THE DISCLAIMERS SET FORTH ABOVE ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE BARGAIN BETWEEN US AND YOU.</p>
                <p class="western">&nbsp;</p>
                <p class="western">7. Investment Disclaimer.</p>
                <p class="western">You acknowledge and understand that the Services are not intended to supply investment, financial, tax or legal advice. The Services are not investment advice and any observations concerning any security, trading algorithm or investment strategy provided in the Services is not a recommendation to buy, sell or hold such investment or security or to make any other investment decisions. We offer no advice regarding the nature, potential value, risk or suitability of any particular investment strategy, trading algorithm, transaction, security or investment. You acknowledge and agree that any use of the Services, any decisions made in reliance on the Services, including any trading or investment decisions or strategies, are made at your own risk.</p>
                <p class="western">&nbsp;</p>
                <p class="western">8. Professional Advice Disclaimer.</p>
                <p class="western">NEITHER Kuants Wealth Private Limited NOR THE SERVICE IS INTENDED TO PROVIDE LEGAL, TAX OR FINANCIAL ADVICE. Kuants Wealth Private Limited IS NOT A FINANCIAL PLANNER, BROKER OR TAX ADVISOR. Your financial situation is unique, and any information obtained through the Service may not be appropriate for your situation. The use and interpretation of the Services require skill and judgment, and you shall at all times exercise your own judgment in the use of the Services.</p>
                <p class="western">&nbsp;</p>
                <p class="western">9. Limitation of Liability.</p>
                <p class="western">YOU ACKNOWLEDGE AND AGREE THAT WE ARE ONLY WILLING TO PROVIDE ACCESS TO THE SITE AND TO PROVIDE THE SERVICES IF YOU AGREE TO CERTAIN LIMITATIONS OF OUR LIABILITY TO YOU AND TO THIRD PARTIES. NEITHER Kuants Wealth Private Limited NOR ITS DIRECTORS, OFFICERS, EMPLOYEES, CONTRACTORS, AGENTS OR SPONSORS ARE RESPONSIBLE OR LIABLE TO YOU OR ANYONE ELSE FOR ANY LOSS OR INJURY OR ANY INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, EXEMPLARY, PUNITIVE OR OTHER DAMAGES UNDER ANY CONTRACT, NEGLIGENCE, STRICT LIABILITY OR OTHER THEORY ARISING OUT OF OR RELATING IN ANY WAY TO (i) THE USE OF, DELAYS IN OPERATION, TRANSMISSION OR RESPONSE OF, OR INABILITY TO USE THE SITE OR THE SERVICES; (ii) ANY CONTENT CONTAINED ON THE SITES AND/OR THE SERVICES; (iii) STATEMENTS OR CONDUCT POSTED OR MADE PUBLICLY AVAILABLE ON THE SITES AND/OR THE SERVICES; (iv) ANY PRODUCT OR SERVICE PURCHASED OR OBTAINED THROUGH THE SITES; (v) ANY ACTION TAKEN IN RESPONSE TO OR AS A RESULT OF ANY INFORMATION AVAILABLE ON THE SITES OR THE SERVICES; (vi) ANY DAMAGE CAUSED BY MISTAKES, INACCURACIES, OMISSIONS, ERRORS, INTERRUPTIONS OR LOSS OF ACCESS TO, DELETION OF, FAILURE TO STORE, FAILURE TO BACK UP, OR ALTERATION OF ANY CONTENT ON THE SITES OR THE SERVICES, OR (vii) ANY OTHER FAILURE OF PERFORMANCE OF THE SITE OR SERVICES OR OTHER MATTER RELATING TO THE SITE AND/OR THE SERVICES, IN EACH CASE WHETHER OR NOT CAUSED BY EVENTS BEYOND THE CONTROL OF OUR DIRECTORS, OFFICERS, EMPLOYEES, CONTRACTORS, AGENTS OR SPONSORS, INCLUDING, BUT NOT LIMITED TO, ACTS OF NATURE, COMMUNICATIONS LINE FAILURE, THEFT, DESTRUCTION, OR UNAUTHORIZED ACCESS TO THE SITE OR SERVICES OR CONTENT STORED THEREIN. IN NO EVENT SHALL Kuants Wealth Private Limited'S TOTAL LIABILITY TO YOU FOR ANY AND ALL DAMAGES, LOSSES, AND CAUSES OF ACTION (WHETHER IN CONTRACT, TORT, STATUTORY, OR OTHERWISE) EXCEED THE GREATER OF: (i) ONE HUNDRED DOLLARS ($100.00) OR (ii) THE TOTAL AMOUNT PAID OR PAYABLE BY YOU TO US, IF ANY, FOR USING ANY OF THE SERVICES OR THE SITE IN THE THREE (3) MONTHS PRIOR TO THE DATE ON WHICH YOU FIRST ASSERT A CLAIM. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES OR THE LIMITATION OR EXCLUSION OF CERTAIN TYPES OF LIABILITY. ACCORDINGLY, SOME OF THE ABOVE LIMITATIONS AND DISCLAIMERS MAY NOT APPLY TO YOU. TO THE EXTENT THAT WE MAY NOT, AS A MATTER OF APPLICABLE LAW, DISCLAIM ANY IMPLIED WARRANTY OR LIMIT LIABILITIES, THE SCOPE, AND DURATION OF SUCH WARRANTY AND THE EXTENT OF OUR LIABILITY WILL BE THE MINIMUM PERMITTED UNDER SUCH APPLICABLE LAW.</p>
                <p class="western">&nbsp;</p>
                <p class="western">10. Release.</p>
                <p class="western">To the extent permitted under applicable laws, you hereby release Kuants Wealth Private Limited from any liability related to (a) any incorrect or inaccurate Content posted on the Services, whether caused by any user of the Services (including, without limitation, any Registered User) or by any of the equipment or programming associated with or utilized in the Services; (b) the conduct, whether online or offline, of any user of the Services (including, without limitation, any Registered User); (c) any loss or damage caused by Content posted on the Services or transmitted by and to Registered Users, or any interactions between users of the Site (including, without limitation, any Registered User), whether online or offline; and (d) any error, omission, interruption, deletion, defect, delay in operation or transmission, communications line failure, theft or destruction or unauthorized access to, or alteration of, user or Registered User communications. If you are a California resident, you hereby waive California Civil Code Section 1542, which states: "A general release does not extend to claims which the creditor does not know or suspect to exist in his favor at the time of executing the release, which, if known by him must have materially affected his settlement with the debtor."</p>
                <p class="western">&nbsp;</p>
                <p class="western">11. Termination.</p>
                <p class="western">This Agreement shall remain effective until terminated in accordance with its own terms and conditions. You agree that Kuants Wealth Private Limited, in its sole discretion, may terminate your password, account (in whole or in part), or use of the Site or Services, and remove and discard any Content within the Sites, at any time and for any reason. You agree that any actions taken under this Section may be effective without prior notice to you. YOU AGREE THAT WE WILL NOT BE LIABLE TO YOU OR ANY OTHER PARTY FOR ANY TERMINATION OF YOUR ACCESS TO THE SITE OR SERVICES OR DELETION OF YOUR ACCOUNT OR YOUR SUBMISSION MATERIALS. In the event of termination, however, those Sections in this Agreement which, by their nature, survive termination of the Agreement shall so survive. Specifically, and without limitation, the license you have granted to Kuants Wealth Private Limited and to third parties to use any Shared Content survives the termination of this Agreement.</p>
                <p class="western">&nbsp;</p>
                <p class="western">12. General Information.</p>
                <p class="western">This Agreement constitutes the entire agreement and understanding between you and Kuants Wealth Private Limited and governs your use of the Site and the Services, superseding any prior agreements between you and Kuants Wealth Private Limited This Agreement and the relationship between you and Kuants Wealth Private Limited shall be governed by and construed in accordance with the laws of the State of New York, without regard to its conflict of law provisions. The failure of Kuants Wealth Private Limited to exercise or enforce any right or provision of this Agreement shall not constitute a waiver of such right or provision. If any provision of this Agreement is found by a court of competent jurisdiction to be unlawful, void or for any reason unenforceable, then that provision shall be deemed severed herefrom and shall not affect the validity and enforceability of any remaining provisions. The section titles in this Agreement are for convenience purposes only and have no legal or contractual effect. This Agreement is not assignable, transferable or sub-licensable by you. However, we may assign this Agreement to any third party whom we choose without your consent and/or without notice to you. No waiver by Kuants Wealth Private Limited of any breach or default hereunder shall be deemed a waiver of any preceding or subsequent breach or default. You acknowledge that we have the right hereunder to seek an injunction, if necessary, to stop or prevent a breach of your obligations hereunder.</p>
                <p class="western">&nbsp;</p>
                <p class="western">13. Electronic Communications.</p>
                <p class="western">You acknowledge and understand that (a) we can only give you the benefits of accessing the Site and using the Services by conducting business through the Internet, and therefore we need you to consent to our giving you Communications (defined below) electronically, and (b) this Section 21 informs you of your rights when receiving Communications from us electronically. For contractual purposes, you: (i) consent to receive communications from us in an electronic form and (ii) agree that all terms and conditions, agreements, notices, documents, disclosures, and other communications (&ldquo;Communications&rdquo;) that we provide to you electronically satisfy any legal requirement that such Communications would satisfy if they were in writing. Your consent to receive Communications and do business electronically, and our agreement to do so, applies to all of your interactions and transactions with us. The foregoing does not affect your non-waivable rights. You may also receive a copy of this Agreement. You may withdraw your consent to receive Communications electronically by contacting us in the manner described below. If you withdraw your consent, from that time forward, you must stop using the Site and Services. The withdrawal of your consent will not affect the legal validity and enforceability of any obligations or any electronic Communications provided or business transacted between us prior to the time you withdraw your consent.</p>
                <p class="western">&nbsp;</p>
                <p class="western">Please keep us informed of any changes in your email or mailing address so that you continue to receive all Communications without interruption.</p>
                <p class="western">&nbsp;</p>
                <p class="western">14. Modification of Services.</p>
                <p class="western">We reserve the right to modify or discontinue the Site and any or all of the Services with or without notice to you. We will not be liable to you or any third party should we exercise our right to modify or discontinue the Site and/or any or all of the Services. If you object to any such changes, your sole recourse will be to cease access to the Site and/or Services, as applicable. Continued access to the Site and/or Services, as applicable, following notice of any such changes, will indicate your acknowledgment of such changes and satisfaction with the Site and/or Services, as applicable, as so modified.</p>
                <p class="western">15. Amendments and Modifications to this Agreement.</p>
                <p class="western">Kuants Wealth Private Limited may amend or modify this Agreement from time to time and at any time. If any such amendment or modification is material, we will post notice of it on the Site&rsquo;s homepage or by email to Registered Users. Your access to the Site and use of the Services following any such amendment or modification shall be deemed your acceptance of such amendment and modification. You agree to review the Agreement periodically to be aware of such amendments and modifications.</p>
                </div>
                <br/>
                <br/>
                <div id="Privacy-Policy">
                <h1 >Privacy Policy</h1>
                <p>Kuants Wealth Private Limited Pvt. Ltd. (Kuants Wealth Private Limited) is strongly committed to protecting the privacy of its customers and has taken all necessary and reasonable measures to protect the confidentiality of the customer information and its transmission through the world wide web and it shall not be held liable for disclosure of the confidential information when in accordance with this Privacy Commitment or in terms of the agreements, if any, with the Customers.</p>
                <p>Kuants Wealth Private Limited Pvt. Ltd. (Kuants Wealth Private Limited) endeavors to safeguard and ensure the security of the information provided by the Customer.</p>
                <p>The Customer would be required to cooperate with Kuants Wealth Private Limited Pvt. Ltd. (Kuants Wealth Private Limited) in order to ensure the security of the information, and it is recommended that the Customers necessarily choose their passwords carefully such that no unauthorized access is made by a third party. To make the password complex and difficult for others to guess, the Customers should use a combination of alphabets, numbers and special characters (like ! @, #, $, etc.). Customers should undertake not to disclose their password to anyone or keep any written or another record of the password such that a third party could access it.Kuants Wealth Private Limited Pvt. Ltd. (Kuants Wealth Private Limited) undertakes not to disclose the information provided by the Customers to any person, unless such action is necessary to: Conform to legal requirements or comply with legal process; Protect and defend Kuants Wealth Private Limited Pvt. Ltd. (Kuants Wealth Private Limited)' or its Affiliates' rights, interests or property; Enforce the terms and conditions of the products or services; or Act to protect the interests of Kuants Wealth Private Limited Pvt. Ltd. (Kuants Wealth Private Limited), its Affiliates, or its members, constituents or of other persons.</p>
                <p>The Customers shall not disclose to any other person, in any manner whatsoever, any information relating to Kuants Wealth Private Limited Pvt. Ltd. (Kuants Wealth Private Limited) or its Affiliates of a confidential nature obtained in the course of availing the services through the website. Failure to comply with this obligation shall be deemed a serious breach of the terms herein and shall entitle Kuants Wealth Private Limited Pvt. Ltd. (Kuants Wealth Private Limited) or its Affiliates to terminate the services, without prejudice to any damages, to which the customer may be entitled otherwise.</p>
                <p>Kuants Wealth Private Limited Pvt. Ltd. (Kuants Wealth Private Limited) will limit the collection and use of customer information only on a need-to-know basis to deliver better service to the customers.Kuants Wealth Private Limited Pvt. Ltd. (Kuants Wealth Private Limited) may use and share the information provided by the Customers with its Affiliates and third parties for providing services and any service-related activities such as collecting subscription fees for such services, and notifying or contacting the Customers regarding any problem with, or the expiration of, such services. In this regard, it may be necessary to disclose the customer information to one or more agents and contractors of Kuants Wealth Private Limited Pvt. Ltd. (Kuants Wealth Private Limited) and their sub-contractors, but such agents, contractors, and sub-contractors will be required to agree to use the information obtained from Kuants Wealth Private Limited Pvt. Ltd. (Kuants Wealth Private Limited) only for these purposes.</p>
                <p>The Customer authorizes Kuants Wealth Private Limited Pvt. Ltd. (Kuants Wealth Private Limited) to exchange, share, part with all information related to the details and transaction history of the Customers to its Affiliates / banks / financial institutions / credit bureaus / agencies/participation in any telecommunication or electronic clearing network as may be required by law, customary practice, credit reporting, statistical analysis and credit scoring, verification or risk management and shall not hold Kuants Wealth Private Limited Pvt. Ltd. (Kuants Wealth Private Limited) liable for use or disclosure of this information.</p>
                <p>BY REGISTERING FOR OR USING THE SITE owned, run, hosted by Kuants Wealth Private Limited, YOU SIGNIFY YOUR ACCEPTANCE OF THIS PRIVACY STATEMENT. IF YOU DO NOT AGREE TO THIS PRIVACY STATEMENT, YOU CANNOT USE THE SITE. We reserve the right to modify this Statement at any time by posting a notice on the Site&rsquo;s home page. (If we consider it appropriate, we may also provide additional notice of significant changes). Your use of the Site after the date of the last modification indicates to us that you agree to the changes.</p>
                <p>a) Email Communications</p>
                <p>You may receive a confirmation when you open an email from us. We use this confirmation to improve our customer service.</p>
                <p>b) Aggregate Information</p>
                <p>We collect statistical information about how both unregistered and registered users, collectively, use the Services ("Aggregate Information"). Some of this information is derived from Personal Information. This statistical information is not Personal Information and cannot be tied back to you, your Account or your web browser.</p>
                <p>c) Email Communications with Us</p>
                <p>As part of the Services, you may occasionally receive email and other communications from us, such as communications relating to your Account or new features or promotional activities related to Kuants Wealth Private Limited</p>
                <p>d) Information Disclosed for Our Protection and the Protection of Others</p>
                <p>&nbsp;</p>
                <p>We also reserve the right to access, read, preserve, and disclose any information as it reasonably believes is necessary to (i) satisfy any applicable law, regulation, legal process or (i) governmental request, (ii) enforce the Terms of Service, including investigation of potential violations thereof, (iii) detect, prevent, or otherwise address fraud, security or technical issues, (iv) respond to user support requests, or (v) protect our rights, property or safety, our users and the public. This includes exchanging information with other companies and organizations for fraud protection and spam/malware prevention.</p>
                <p>Risk Disclosure Statement</p>
                <p>INTRODUCTION</p>
                <p>Welcome to Kuants Wealth Private Limited Kuants is provided by Kuants Wealth Private Limited Pvt. Ltd, a web-based platform to create, and backtest trading algorithms.</p>
                <p>Creating strategy is a process to input entry and exit conditions involving technical indicators, stop loss percentage, take profit percentage, instrument, etc and form a trading strategy, hereafter referred to as "trading algo" or "algo" or "algorithms".</p>
                <p>Backtesting is the process of testing a trading strategy on relevant historical data to ensure its viability before the trader risks any actual capital. A trader can simulate the trading of a strategy over an appropriate period of time and analyze the results for the levels of profitability and risk. Kuants Wealth Private Limited Pvt. Ltd. (Kuants Wealth Private Limited) strives to give you accurate information on your trading strategies and your algorithms, however, in case of any inconsistency, the company cannot be held liable in case of any monetary, mental or loss in any form.</p>
                <p>Using Kuants Wealth Private Limited Pvt. Ltd. (Kuants Wealth Private Limited)&rsquo;s Services, including its deploy services, presents several different types of risk. We have summarized these below. You should read and understand these risks before you use any of Kuants Wealth Private Limited Pvt. Ltd. (Kuants Wealth Private Limited)&rsquo;s services.</p>
                <p>1. RISKS</p>
                <p>The risks that can arise from using Kuants Wealth Private Limited Pvt. Ltd. (Kuants Wealth Private Limited)&rsquo;s Site and Services fall into two broad categories:</p>
                <p>1. Risks inherent generally in using Internet-based technology;</p>
                <p>2. Risks inherent in creating, backtesting;</p>
                <p>&nbsp;</p>
                <p>ANY PERMUTATION OR COMBINATION OF THE OCCURRENCE OF THE POTENTIAL EVENTS THAT DEFINE THE RISKS DESCRIBED IN THIS DISCLOSURE STATEMENTS CAN LEAD TO A TOTAL OR PARTIAL LOSS OF OPERABILITY, RESPONSIVENESS, FUNCTIONALITY, AND FEATURES THAT COULD MATERIALLY AND ADVERSELY AFFECT YOUR USE OF Kuants Wealth Private Limited OR kuants.in</p>
                <p>1. Risks of Using Internet-based Technology - Generally</p>
                <p>The Internet-related technological risks arising from using Kuants Wealth Private Limited Pvt. Ltd. (Kuants Wealth Private Limited)&rsquo;s Site and Services to write, test, analyze, and run trading algorithms and related trading strategies fall into three categories: (a) risks related to Kuants Wealth Private Limited Pvt. Ltd. (Kuants Wealth Private Limited)&rsquo;s software; (b) risks related to Kuants Wealth Private Limited Pvt. Ltd. (Kuants Wealth Private Limited)&rsquo;s computing and communications infrastructure; and (c) risks related to your software, hardware, and Internet connectivity.</p>
                <p>a. Kuants Wealth Private Limited Pvt. Ltd. (Kuants Wealth Private Limited)&rsquo;s software might fail or work properly.</p>
                <p>i. All software is subject to inadvertent programming errors and bugs embedded in the code comprising that software. Any of these errors and bugs can cause the software in which they are located to fail or not work properly. The applications software used to operate Kuants Wealth Private Limited Pvt. Ltd. (Kuants Wealth Private Limited)&rsquo;s Site and Services depends is subject to this risk. Despite testing and on-going monitoring and maintenance, inadvertent errors and bugs may still cause a failure inKuants Wealth Private Limited Pvt. Ltd. (Kuants Wealth Private Limited)&rsquo;s applications software.</p>
                <p>ii. We may update or revise our applications software in ways that cause some of its functionality or features to be lost or diminished. Any such loss or diminution could make Kuants Wealth Private Limited Pvt. Ltd. (Kuants Wealth Private Limited) less valuable to you, cause certain functions and features in your algorithms to fail, and require you to change your algorithms and related trading strategies.</p>
                <p>b.Kuants Wealth Private Limited Pvt. Ltd. (Kuants Wealth Private Limited)&rsquo;s computing and communications infrastructure may fail.</p>
                <p>The operation of Kuants Wealth Private Limited Pvt. Ltd. (Kuants Wealth Private Limited)&rsquo;s Site and Services depend heavily on our infrastructure of computing and communications systems. The operation of this infrastructure is subject to several risks:</p>
                <p>i. Any or all of the systems comprising our infrastructure could entirely or partially fail, function erratically, or function very slowly (thereby leading to latency, i.e., delays in receipt of and response to user requests).</p>
                <p>ii. We may inadvertently cause a systems failure during planned or unplanned system maintenance.</p>
                <p>iii. We may undertake software upgrades, either planned or unplanned, that take longer to implement or that causes your computer system or Internet connectivity to fail.</p>
                <p>iv. We may change or remove functions and features whose change or removal causes your system to fail, function erratically, or function very slowly.</p>
                <p>c. Your computer system and your Internet connectivity may fail.</p>
                <p>Any of the components of your computer system and/or your Internet connectivity could fail entirely, function erratically, or function very slowly. The result of any of these occurrences could make it difficult or impossible for you to access the Kuants Wealth Private Limited Pvt. Ltd. (Kuants Wealth Private Limited) Site or use the Kuants Wealth Private Limited Pvt. Ltd. (Kuants Wealth Private Limited) Services.</p>
                <p>You may incur losses (or fail to gain profits) while trading securities. You should discuss the risks of trading with the broker-dealer where you maintain an account or other investment professional. Kuants Wealth Private Limited Pvt. Ltd. (Kuants Wealth Private Limited) provides you only with trading technology and can provide no investment, financial, regulatory, tax or legal advice.</p>
                <p>2. Risks in Create, and Backtest Algos (Algorithms)</p>
                <p>Creating and backtesting trading algorithms is subject to several risks, any of which can cause your algorithms to not function as you had intended or fail to achieve one or more of the objectives of your algorithms. Algorithmic trading is rapidly changing as a practice and as an industry. Models of markets used to write and test trading algorithms are inherently limited and often fail to perform as expected. In addition, trading algorithms are implemented in software programming code, and no matter how well designed and thoroughly tested, any such code can have logical errors and bugs that cause the algorithms to malfunction or suggest trades that, if executed, would result in losses. It is your obligation to thoroughly and appropriately test any trading algorithm before you deploy it and to continually monitor the operation of any deployed trading algorithm to ensure it is running properly and in compliance with any applicable rules</p>
                <p>a. Your algorithm may be designed on the basis of an incorrect understanding of technical indicators which may not work as expected.</p>
                <p>b. Your algorithm may contain logical errors in the way you understand the indicators and comparators.</p>
                <p>c. Errors may exist in the data used for testing your algorithm or the applicable model of the market.</p>
                <p>d. Your algorithm might appear to succeed in a backtesting environment using historical data,</p>
                <p>e. Your algorithm might appear to succeed with some data sources, but fail when using other data sources in our system.</p>
                <p>f. Your algorithm may not achieve the returns you anticipate. There are no guarantees, or even expectations, that can be made about the future behavior of an algorithm.</p>
                <p>g. Backtesting Cannot Assure Actual Results.</p>
                <p>It is not possible for a computer model to truly predict what might have happened if an algorithm-based trading strategy was in play in a live trading environment. For example, the implementation of such a strategy can itself have an impact on the market, and the model may fail to account for real-life factors that impact the model. Moreover, the model may fail to account for execution costs including broker commissions, fees, and trading slippage.</p>
                <p>A promising model result does not necessarily predict a successful strategy. A backtest might be over-fitted to past data, and fail when the strategy is applied to new, live data. Your algorithm might not handle market conditions that cannot be reasonably anticipated, i.e., a &ldquo;flash crash&rdquo; or an exchange outage. These market conditions, by definition, will not have been tested.</p>
                <p>h.The relevant market might fail or behave unexpectedly. Market centers in which you seeking to implement your trading strategy may fail or behave incorrectly because of technical reasons relating to infrastructure, connectivity, and similar factors.</p>
                <p>Your algorithm might suffer from adverse market conditions. Those conditions can include a lack of liquidity and abrupt and unwarranted price swings. Also possible are late market openings, early market closings, market chaos, and mid-day trading pauses, and other such disruptive events.</p>
                <p>i. You may receive incorrect information, or be unable to get information, about your orders, your positions, or market conditions. Incorrect actions may be taken, or corrective actions may not be taken, because of inaccurate or missing information. In addition, you may be unable to terminate or edit your algorithm.</p>
                <p>k. Malicious and criminal activities might cause your algorithms and strategy to fail.</p>
                <p>All computers and networks are subject to malicious &ldquo;hacking&rdquo; attacks and criminal activities designed to misappropriate the intellectual property, compromise personally identifiable information, steal funds, or any combination of such purposes. These attacks might be attacks on a target of opportunity or specifically targeted. Any such attack could cause the system so attacked to function improperly or not at all and could result in the misappropriation of your intellectual property, the compromise of your personally identifiable information and personal financial information, the theft of your funds and can cause your algo to be misbehave, malfunction or behave erratically. Kuants Wealth Private Limited cannot be held liable and no legal action can be initiated against Kuants Wealth Private Limited, in any case of an external attack by a malicious entity that leads to disclosure of personal data, algorithms or any other data a user has created, submitted or stored with Kuants Wealth Private Limited Kuants Wealth Private Limited, in any case, be held liable to any loss of intellectual property, content, harm to reputation, damage, etc.</p>
               </div>
               <div id="Refund-Policy">
                <h1 >Refund Policy</h1>
                <p>We do not offer any refund on any subscription, live trading, or in any other condition. The company cannot be held liable in an case, including but not limited to technical, trading or any other concern of the user. The user acknowledges that any transaction made, from live trading to payments, on, by, through the platform is as per his discretion and is fully aware of the risks and features provided.</p>
               </div>     
                </div>         
            </div>
        );
    }
}

export default Terms;